<Project>

  <PropertyGroup>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <Company>vilminessa</Company>
    <Product>Parrhesia</Product>
    <Copyright>Copyright © 2026 vilminessa</Copyright>
    <NeutralLanguage>ru-RU</NeutralLanguage>
  </PropertyGroup>

</Project>
